# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://yueguo1997.github.io/modules/"

git_url = "https://github.com/yueguo1997/modules/tree/main/"

def custom_doc_links(name): return None
